version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      PORT: 3000
      POSTGRES_HOST: "database"
      POSTGRES_DB: "tmdb_db"
      POSTGRES_USER: "joseMoya"
      POSTGRES_PASSWORD: "db_password"
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ".:/back"

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: "tmdb_db"
      POSTGRES_USER: "joseMoya"
      POSTGRES_PASSWORD: "db_password"
    ports:
      - "5432:5432"
    volumes:
      - "db_volume:/var/lib/postgresql"

volumes:
  db_volume:
    external: true
